package com.dyy.yonxin.library2.cacheforandroid.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dyy.yonxin.library2.cacheforandroid.bean.DBUser;
import com.dyy.yonxin.library2.cacheforandroid.bean.DBUserNoKey;
import com.dyy.yonxin.library2.cacheforandroid.bean.CacheUser;

import com.dyy.yonxin.library2.cacheforandroid.db.DBUserDao;
import com.dyy.yonxin.library2.cacheforandroid.db.DBUserNoKeyDao;
import com.dyy.yonxin.library2.cacheforandroid.db.CacheUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBUserDaoConfig;
    private final DaoConfig dBUserNoKeyDaoConfig;
    private final DaoConfig cacheUserDaoConfig;

    private final DBUserDao dBUserDao;
    private final DBUserNoKeyDao dBUserNoKeyDao;
    private final CacheUserDao cacheUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBUserDaoConfig = daoConfigMap.get(DBUserDao.class).clone();
        dBUserDaoConfig.initIdentityScope(type);

        dBUserNoKeyDaoConfig = daoConfigMap.get(DBUserNoKeyDao.class).clone();
        dBUserNoKeyDaoConfig.initIdentityScope(type);

        cacheUserDaoConfig = daoConfigMap.get(CacheUserDao.class).clone();
        cacheUserDaoConfig.initIdentityScope(type);

        dBUserDao = new DBUserDao(dBUserDaoConfig, this);
        dBUserNoKeyDao = new DBUserNoKeyDao(dBUserNoKeyDaoConfig, this);
        cacheUserDao = new CacheUserDao(cacheUserDaoConfig, this);

        registerDao(DBUser.class, dBUserDao);
        registerDao(DBUserNoKey.class, dBUserNoKeyDao);
        registerDao(CacheUser.class, cacheUserDao);
    }
    
    public void clear() {
        dBUserDaoConfig.clearIdentityScope();
        dBUserNoKeyDaoConfig.clearIdentityScope();
        cacheUserDaoConfig.clearIdentityScope();
    }

    public DBUserDao getDBUserDao() {
        return dBUserDao;
    }

    public DBUserNoKeyDao getDBUserNoKeyDao() {
        return dBUserNoKeyDao;
    }

    public CacheUserDao getCacheUserDao() {
        return cacheUserDao;
    }

}
